[workspace]
# 2 is lateast that should be used
resolver = "2"
# you actually can use start here...
members = ["common", "y*"]

# add this so all libs will have those!
[workspace.dependencies]
rstest = "0.26"
itertools = "0.14"
common = { path = "../common" }
