[workspace]
members = [
    "common",
    "y2015",
    "y2017",
    "y2023",
    "y2025",
]
resolver = "2"

[workspace.dependencies]
itertools = "0.14"
rstest = "0.26"

[workspace.dependencies.common]
path = "../common"
