[package]
name = "y2025"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14"
common = { path = "../common" }
good_lp = { version = "1.14.2", features = ["highs"], default-features = false }

[dev-dependencies]
rstest = "0.26"
